version: "3.8"
services:
  ubuntu:
    image: "ubuntu"

  console:
    image: "console"
    hostname: "ubuntu-console"
    depends_on:
      - ubuntu
    volumes:
      - type: bind
        source: .
        target: /home/hostuser/
      - type: bind
        source: "$SSH_AUTH_SOCK"
        target: /ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/ssh-auth.sock
    container_name: "ubuntu-console"

